apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "charts-event-worker.fullname" . }}
  {{- if .Values.global.keda.autoscalingPaused }}
  annotations:
    autoscaling.keda.sh/paused: "true"
  {{- end }}
spec:
  scaleTargetRef:
    name:          {{ include "charts-event-worker.fullname" . }}
  pollingInterval: {{ .Values.global.keda.pollingInterval }}
  cooldownPeriod:  {{ .Values.global.keda.cooldownPeriod }}
  initialCooldownPeriod: {{ .Values.global.keda.initialCooldownPeriod }}
  idleReplicaCount: {{ .Values.global.keda.idleReplicaCount }}
  minReplicaCount: {{ .Values.global.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.global.keda.maxReplicaCount }}
  fallback:
    failureThreshold: 3
    replicas: {{ default .Values.global.keda.minReplicaCount .Values.global.keda.fallbackReplicasCount }}
  triggers:
    {{- range .Values.global.keda.triggers.azureServiceBus.triggers }}
    {{- end }}