{{- if .Values.global.monitoring.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts-event-worker.fullname" . }}
  labels:
    {{- include "charts-event-worker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ (index .Values.global.monitoring.metrics.ports 0).containerPort }}
      targetPort: {{ (index .Values.global.monitoring.metrics.ports 0).name | default "metrics" }}
      protocol: TCP
      name: {{ (index .Values.global.monitoring.metrics.ports 0).name | default "metrics" }}
  selector:
    {{- include "charts-event-worker.selectorLabels" . | nindent 4 }}
{{- end -}}