{{- if .Values.secEnvVarsEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "charts-core.fullname" . }}-secure"
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{- include "charts-core.labels" . | nindent 4 }}
data:
  {{- if .Values.secEnvVars -}}
  {{ range $key, $val := .Values.secEnvVars }}
    {{ $key }}: {{ $val | b64enc }}
  {{ end }}
  {{- end }}
{{- end -}}