{{- if .Values.envVarsEnabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "charts-core.fullname" . }}"
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    {{- include "charts-core.labels" . | nindent 4 }}
data:
  {{- if .Values.envVars -}}
  {{ range $key, $val := .Values.envVars }}
    {{ $key }}: {{ $val | quote }}
  {{ end }}
  {{- end }}
{{- end -}}