{{- if .Values.global.serviceAccount.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name:  {{ include "charts-core.fullname" . }}
rules:
{{- range .Values.global.serviceAccount.rules }}
  - apiGroups: 
    {{- toYaml .apiGroups | nindent 4 }}
    resources: 
    {{- toYaml .resources | nindent 4 }}
    verbs: 
    {{- toYaml .verbs | nindent 4 }}
{{- end }}
{{- end }}