{{- if .Values.global.fileShareMount.enabled -}}
apiVersion: v1
data:
  azurestorageaccountkey: {{ .Values.global.fileShareMount.storageAccountKey | b64enc }}
  azurestorageaccountname: {{ .Values.global.fileShareMount.storageAccountName | b64enc }}
kind: Secret
metadata:
  name: {{ include "charts-dotnet-core.fullname" . }}-file-share
type: Opaque
{{- end -}}
