{{- if and .Values.global.service.enabled (not .Values.global.canary.enabled) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts-dotnet-core.fullname" . }}
  labels:
    {{- include "charts-dotnet-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.global.service.type }}
  ports:
    - port: {{ .Values.global.service.port }}
      targetPort: {{ (index .Values.global.image.ports 0).containerPort | default "http" }} 
      protocol: TCP
      name: {{ (index .Values.global.image.ports 0).name | default "http" }}
  selector:
    {{- include "charts-dotnet-core.selectorLabels" . | nindent 4 }}
{{- end -}}