apiVersion: v2
description: EcoVadis Helm chart for K8s Cron Job
name: charts-cron-job
type: application
version: 3.0.0
dependencies:
- name: charts-core
  version: 3.0.0
  repository: "https://ecovadiscode.github.io/charts/"