{{- if .Values.global.defaultNetworkPolicyEnabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "charts-core.fullname" . }}
  labels:
    {{- include "charts-core.labels" . | nindent 4 }}
    networkPolicyType: default
spec:
  podSelector:
    matchLabels:
      {{- include "charts-core.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
  - Ingress
  ingress:
    - from: #any pod in current namespace
        - podSelector: {}
  {{- if not .Values.global.allowAllInternalClusterTrafficNetworkPolicy }}
    - from: #any pod from *-infra, *-backend, *-frontend namespace
        - namespaceSelector:
            matchLabels:
              environment: {{ (split "-" .Release.Namespace)._0 }}
  {{ else }}
    - from:
        - namespaceSelector: {}
  {{- end }}
  {{- if .Values.global.monitoring.servicemonitor.enabled }}
    - from:
        - namespaceSelector:
            matchLabels:
              environment: {{ .Values.global.monitoring.prometheusNamespace }}
  {{- end }}
    - from: #outside world - sentry, optimizely, etc
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 443
        - port: 80
        - port: 8443
        - port: 8000
  {{- if .Values.global.monitoring.metrics.enabled }}
        - port: {{ .Values.global.monitoring.metrics.port }}  #metrics port
  {{- end }}
  {{- if .Values.global.servicebusNetworkPolicyEnabled }}
        - port: 5671  #servicebus
  {{- end }}
    - from: #vnet address space
        - ipBlock:
            cidr: {{ .Values.global.vnetCidr }}
      ports:
        - port: 443
        - port: 80
  egress:
    - to: #any pod in current namespace
        - podSelector: {}
    - to: #kube-dns
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
  {{- if not .Values.global.allowAllInternalClusterTrafficNetworkPolicy }}
    - to: #any pod from *-infra, *-backend, *-frontend namespace
        - namespaceSelector:
            matchLabels:
              environment: {{ (split "-" .Release.Namespace)._0 }}
  {{ else }}
    - to:
        - namespaceSelector: {}
  {{- end }}
      ports:
        - port: 8443
        - port: 8000
        - port: 80
        - port: 443
  {{- if .Values.global.elasticNetworkPolicyEnabled }} 
    - to:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.global.elasticNamespace }}
      ports:
        - port: 9200
  {{- end }}
    - to: #any pod in monitoring namespace
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - port: 9200
        - port: 8200
    - to: #any elastic or apm outside of the cluster
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 9200
        - port: 8200
  {{- if .Values.global.redisNetworkPolicyEnabled }}
    - to: #redis
        - ipBlock:
            cidr: {{ .Values.global.vnetCidr }}
      ports:
        - port: 6380
  {{- end }}
    - to: #outside world - sentry, optimizely, etc
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 443
        - port: 80
  {{- if .Values.global.servicebusNetworkPolicyEnabled }}
        - port: 5671  #servicebus
  {{ end }}
    - to: #vnet addressspace - mssql, servicebus
        - ipBlock:
            cidr: {{ .Values.global.vnetCidr }}
      ports:
  {{- if .Values.global.mongodbNetworkPolicyEnabled }}
        - port: 1024  #mongodb
          endPort: 65535
  {{- else }}
    {{- if .Values.global.zyteProxyNetworkPolicyEnabled }}
        - port: 8010   #Zyte Proxy
        - port: 8011
        - port: 8014
    {{- end }}
    {{- if .Values.global.postgresNetworkPolicyEnabled }}
        - port: 5432  #postgres
    {{- end }}
    {{- if .Values.global.sqlNetworkPolicyEnabled }}
        - port: 1433  #mssql
    {{- end }}
    {{- if .Values.global.lnmElasticNetworkPolicyEnabled }}
        - port: 9201
    {{- end }}
    {{- if .Values.global.cosmosNetworkPolicyEnabled }}
        - port: 10255
    {{- end }}
    {{- if .Values.global.elasticNetworkPolicyEnabled }} 
        - port: 9243 #elastic cloud
    {{- end }}
        - port: 8433
        - port: 8000
  {{- end }}
        - port: 433
        - port: 80
        - port: 53
          protocol: UDP
{{- end -}}
