{{- if .Values.global.persistentVolume.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "charts-core.fullname" . }}-pvc-0
spec:
  accessModes:
    - {{ .Values.global.persistentVolume.accessMode }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.global.persistentVolume.size }}
  storageClassName: {{ .Values.global.persistentVolume.storageClassName }}
{{- end }}