{{- range .Values.global.persistentVolumes }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ include "charts-core.fullname" $ }}-{{ .name }}-pvc
spec:
  accessModes:
    - {{ .accessMode | default "ReadWriteMany" }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .size | default "1Gi" }}
  storageClassName: {{ include "charts-core.fullname" $ }}-azurefile-csi
{{- end }}
