{{- if .Values.global.persistentVolumes }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "charts-core.fullname" . }}-azurefile-csi
  labels:
    {{- include "charts-core.labels" . | nindent 4 }}
provisioner: file.csi.azure.com
parameters:
  skuName: {{ .Values.global.persistentVolumesSkuName | default "Standard_LRS" }}
  tags: >-
    team={{ .Values.global.additionalLabels.team | lower }},
    environment={{ (split "-" .Release.Namespace)._0 | lower }}
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
{{- end }}
