{{- if .Values.global.canary.enabled }}
apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: error-rate-{{ include "charts-core.fullname" . }}
spec:
  provider: 
    address: {{ include "charts-core.prometheusServer" . | quote }}
    type: prometheus
  query: |
{{- if and .Values.global.monitoring.servicemonitor.enabled .Values.global.monitoring.metrics.enabled }}
    100 - sum by (job) 
      (rate(http_requests_received_total{namespace="{{ .Release.Namespace }}",job="{{ include "charts-core.fullname" . }}-canary",code!~"5.*"}[1m]))
        / ignoring(code) group_left
    sum by (job) 
      (rate(http_requests_received_total{namespace="{{ .Release.Namespace }}",job="{{ include "charts-core.fullname" . }}-canary"}[1m])) * 100
{{- else }}
    100 - sum by (exported_service) 
      (rate(traefik_service_requests_total{exported_service=~"{{ .Release.Namespace }}-{{ include "charts-core.fullname" . }}-canary.*",code!~"5.*"}[2m]))
        / ignoring(code) group_left
    sum by (exported_service) 
      (rate(traefik_service_requests_total{exported_service=~"{{ .Release.Namespace }}-{{ include "charts-core.fullname" . }}-canary.*"}[2m])) * 100
{{- end }}
---
apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: response-time-{{ include "charts-core.fullname" . }}
spec:
  provider:
    address: {{ include "charts-core.prometheusServer" . | quote }}
    type: prometheus
  query: |
{{- if and .Values.global.monitoring.servicemonitor.enabled .Values.global.monitoring.metrics.enabled }}
    sum by (job) (
      (rate(http_request_duration_seconds_sum {namespace="{{ .Release.Namespace }}",job="{{ include "charts-core.fullname" . }}-canary"}[1m] ) /
        rate(http_request_duration_seconds_count {namespace="{{ .Release.Namespace }}",job="{{ include "charts-core.fullname" . }}-canary"}[1m] )) > 0 )
{{- else }}
    sum by (exported_service) (
      (rate(traefik_service_request_duration_seconds_sum{exported_service=~"{{ .Release.Namespace }}-{{ include "charts-core.fullname" . }}-canary.*"}[2m]) /
        rate(traefik_service_requests_total{exported_service=~"{{ .Release.Namespace }}-{{ include "charts-core.fullname" . }}-canary.*"}[2m])) > 0)    
{{- end }}
{{- end }}