{{- if .Values.ingressRoutes.enabled -}}
{{ if .Values.ingressRoutes.tlsRouteEnabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "chart.fullname" . }}-https
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule  
      match: Host(`{{ .Values.ingressRoutes.host }}`)
      services:
        - kind: Service
          name: {{ include "chart.fullname" . }}
          namespace: {{ .Release.Namespace }}
          port: {{ .Values.ingressRoutes.port }}
  tls: {}
{{- end }}
{{ if and .Values.ingressRoutes.nonTlsRouteEnabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "chart.fullname" . }}-http
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule  
      match: Host(`{{ .Values.ingressRoutes.host }}`)
      {{- if and .Values.ingressRoutes.redirectToHttps .Values.ingressRoutes.tlsRouteEnabled }}
      middlewares:
        - name: redirect-https
      {{- end }}
      services:
        - kind: Service
          name: {{ include "chart.fullname" . }}
          namespace: {{ .Release.Namespace }}
          port: {{ .Values.ingressRoutes.port }}
{{- if and .Values.ingressRoutes.redirectToHttps .Values.ingressRoutes.tlsRouteEnabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  redirectScheme:
    permanent: true
    port: '443'
    scheme: https
{{- end }}
{{- end }}
{{- end }}
