{{- if .Values.global.appConfigFilesEnabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "charts-app-reverse-proxy.fullname" . }}-files
  labels:
    {{- include "charts-app-reverse-proxy.labels" . | nindent 4 }}
stringData:
{{- if .Values.global.appConfigFiles.globPattern -}}
  {{ $currentScope := .}}
  {{ range $path, $_ :=  .Files.Glob .Values.global.appConfigFiles.globPattern }}
  {{- with $currentScope}}
{{- $path }}: |-
{{ .Files.Get $path | indent 4 }}
  {{- end }}
  {{ end }}
{{- end -}}
{{- if .Values.global.appConfigFiles.filesList -}}
  {{ $files := .Files }}
  {{- range .Values.global.appConfigFiles.filesList }}
  {{- . }}: |-
{{ $files.Get . | indent 4 }}
  {{- end }}
{{- end -}}
{{- end -}}