apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts-app-reverse-proxy.fullname" . }}
  labels:
    {{- include "charts-app-reverse-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.global.service.type }}
  ports:
    - port: {{ .Values.global.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "charts-app-reverse-proxy.selectorLabels" . | nindent 4 }}
