apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "azdevops-{{ .Values.buildAgentName }}"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"  
data:
  AZP_URL: {{ .Values.devops.AZP_URL | b64enc | quote }}
  AZP_POOL: {{ .Values.devops.AZP_POOL | b64enc | quote }}
  ACR_NAME: {{ .Values.devops.ACR_NAME | b64enc | quote }}