apiVersion: v2
description: EcoVadis Helm chart for K8s Event driven Job
name: charts-job
type: application
version: 2.6.0
dependencies:
- name: charts-core
  version: 2.3.0
  repository: "https://ecovadiscode.github.io/charts/"