apiVersion: v2
description: EcoVadis Helm chart for K8s Cron Job
name: charts-job
type: application
version: 2.1.0
dependencies:
- name: charts-core
  version: 2.1.0
  repository: "https://ecovadiscode.github.io/charts/"