name: PR Gate

on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Assign Team and Persons"
      uses: rowi1de/auto-assign-review-teams@v1.1.3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        org: "EcovadisCode"
        teams: "EcovadisCode/ev-devops"

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Helm tool installer
      uses: azure/setup-helm@v1
      with:
        version: '3.5.4' # default is latest stable
      id: install

    - uses: actions/setup-python@v4
      with:
        python-version: '3.8.2'
        architecture: 'x64'

    - name: Install PyTest
      run: |
        python -m pip install --upgrade pip
        pip install jsonschema pytest jmespath kubernetes

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.2.1

    - name: Run chart-testing (list-changed)
      id: list-changed
      run: |
        changed=$(ct list-changed --config .github/linters/ct.yaml)
        if [[ -n "$changed" ]]; then
          echo "::set-output name=isChanged::true"
          echo "::set-output name=changed::$changed"
        fi

    - name: Helm - Lint Chart
      if: ${{ steps.list-changed.outputs.isChanged }}
      working-directory: ./${{ steps.list-changed.outputs.changed }}
      run: helm lint

    - name: Helm - Render chart
      if: ${{ steps.list-changed.outputs.isChanged }}
      working-directory: ./${{ steps.list-changed.outputs.changed }}
      run: helm template .

    - name: Python - Run Unit Test
      run: pytest
      if: ${{ steps.list-changed.outputs.isChanged }}
      working-directory: ./${{ steps.list-changed.outputs.changed }}
