name: Release a chart

on:
  push:
    branches:
      - master


jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Helm tool installer
        uses: azure/setup-helm@v1
        with:
          version: '3.5.4' # default is latest stable
        id: install

      # - name: Parse Chart.yaml
      #   id: parse-chart
      #   run: |
      #     name=$(yq ".name" < Chart.yaml)
      #     version=$(yq ".version" < Chart.yaml)
      #     echo "::set-output name=tagname::${name}-${version}"
      
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          charts_dir: "."
          CR_PACKAGE_PATH: "packages"
